using NUnit.Framework;
using SemanticKeys;
using UnityEngine;

namespace SemanticKeys.Tests
{
    public class SemanticKeysSettingsTests
    {
        [Test]
        public void GetOrCreateSettings_ReturnsValidInstance()
        {
            // This test ensures the fail-safe creation works even if the asset doesn't exist in the project
            var settings = SemanticKeysSettings.GetOrCreateSettings();

            Assert.IsNotNull(settings);
            Assert.IsInstanceOf<SemanticKeysSettings>(settings);
        }

        [Test]
        public void DefaultValues_AreCorrect()
        {
            // Important to ensure package conventions aren't broken by accidental code changes
            var settings = ScriptableObject.CreateInstance<SemanticKeysSettings>();

            Assert.AreEqual("Assets/Data/SemanticKeys", settings.DomainCreationPath);
            Assert.AreEqual("Assets/Scripts/AutoGenerated", settings.GeneratedCodePath);
            Assert.AreEqual("Game.Constants", settings.GeneratedNamespace);
        }
    }
}