using System;
using System.Collections.Generic;
using UnityEngine;
using System.Linq;

#if UNITY_EDITOR
using UnityEditor;
using System.IO;
using System.Text.RegularExpressions;
#endif

namespace SemanticKeys
{
    [CreateAssetMenu(fileName = "NewKeyDomain", menuName = "SemanticKeys/Key Domain")]
    public class KeyDomain : ScriptableObject
    {
        [Serializable]
        public class KeyDefinition
        {
            [SerializeField] private string _name;
            [SerializeField] private string _guid;
            [TextArea][SerializeField] private string _description;

            public string Name => _name;
            public string Guid => _guid;

            public KeyDefinition(string name)
            {
                _name = name;
                _guid = System.Guid.NewGuid().ToString();
            }

            // Ensures a GUID exists if created via Inspector "+" button
            public void ValidateGuid()
            {
                if (string.IsNullOrEmpty(_guid))
                {
                    _guid = System.Guid.NewGuid().ToString();
                }
            }

            // Forces a new GUID (used when duplicates are detected)
            public void RegenerateGuid()
            {
                _guid = System.Guid.NewGuid().ToString();
            }
        }

        [SerializeField] private string _domainName;
        [SerializeField] private List<KeyDefinition> _keys = new List<KeyDefinition>();

        public string DomainName => _domainName;
        public IEnumerable<KeyDefinition> Keys => _keys;
        public string Guid { get; private set; }

        private void OnEnable()
        {
            if (string.IsNullOrEmpty(Guid)) Guid = System.Guid.NewGuid().ToString();
            if (string.IsNullOrEmpty(_domainName)) _domainName = name;
        }

#if UNITY_EDITOR
        // Called when value is changed in Inspector (including adding items to list)
        private void OnValidate()
        {
            if (string.IsNullOrEmpty(Guid)) Guid = System.Guid.NewGuid().ToString();

            if (_keys != null)
            {
                var seenGuids = new HashSet<string>();
                foreach (var key in _keys)
                {
                    if (key == null) continue;

                    // 1. Ensure it has a GUID (handles fresh entries)
                    key.ValidateGuid();

                    // 2. Check for duplicates (handles Unity list duplication copying values)
                    // If we have seen this GUID already in this iteration, this current key is a copy.
                    if (seenGuids.Contains(key.Guid))
                    {
                        key.RegenerateGuid();
                    }

                    seenGuids.Add(key.Guid);
                }
            }
        }

        public void SetDomainName(string name)
        {
            _domainName = name;
            EditorUtility.SetDirty(this);
        }

        public KeyDefinition AddKey(string name)
        {
            var existing = _keys.FirstOrDefault(k => k.Name.Equals(name, StringComparison.OrdinalIgnoreCase));
            if (existing != null) return existing;

            Undo.RecordObject(this, $"Add Key '{name}'");
            var newKey = new KeyDefinition(name);
            _keys.Add(newKey);
            EditorUtility.SetDirty(this);
            return newKey;
        }

        [ContextMenu("Generate Static Class")]
        public void GenerateCode()
        {
            // 1. Get Settings
            var settings = SemanticKeysSettings.GetOrCreateSettings();
            string folderPath = settings.GeneratedCodePath;
            string targetNamespace = settings.GeneratedNamespace;

            // 2. Ensure Folder Exists
            if (!Directory.Exists(folderPath))
            {
                Directory.CreateDirectory(folderPath);
            }

            // 3. Prepare Content
            string className = SanitizeClassName(_domainName);
            var sb = new System.Text.StringBuilder();

            sb.AppendLine("// ------------------------------------------------------------------------------");
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine($"//     This code was generated by the SemanticKeys tool.");
            sb.AppendLine("//     Runtime changes to this file may cause incorrect behavior and will be lost if");
            sb.AppendLine("//     the code is regenerated.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("// ------------------------------------------------------------------------------");
            sb.AppendLine("");
            sb.AppendLine($"namespace {targetNamespace}");
            sb.AppendLine("{");
            sb.AppendLine($"    using SemanticKeys;");
            sb.AppendLine("");
            sb.AppendLine($"    public static class {className}");
            sb.AppendLine("    {");

            HashSet<string> usedNames = new HashSet<string>();

            foreach (var key in _keys)
            {
                string variableName = SanitizeVariableName(key.Name);

                // Simple collision handling for generated variables
                if (usedNames.Contains(variableName))
                {
                    Debug.LogWarning($"[SemanticKeys] Variable name collision for '{variableName}' in domain '{_domainName}'. Appending index.");
                    int index = 1;
                    while (usedNames.Contains($"{variableName}_{index}")) index++;
                    variableName = $"{variableName}_{index}";
                }
                usedNames.Add(variableName);

                sb.AppendLine($"        public static readonly SemanticKey {variableName} = new SemanticKey(\"{key.Guid}\", \"{key.Name}\", \"{this.Guid}\");");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            // 4. Write to File
            string filePath = Path.Combine(folderPath, $"{className}.cs");

            try
            {
                File.WriteAllText(filePath, sb.ToString());
                Debug.Log($"[SemanticKeys] Generated {className}.cs at {filePath}");
                AssetDatabase.Refresh();
            }
            catch (Exception e)
            {
                Debug.LogError($"[SemanticKeys] Failed to write file: {e.Message}");
            }
        }

        private string SanitizeClassName(string input)
        {
            return Regex.Replace(input, @"[^a-zA-Z0-9_]", "");
        }

        private string SanitizeVariableName(string input)
        {
            string temp = input.Replace(".", "_").Replace(" ", "_");
            temp = Regex.Replace(temp, @"[^a-zA-Z0-9_]", "");
            if (temp.Length > 0 && char.IsDigit(temp[0])) temp = "_" + temp;
            return temp;
        }
#endif
    }

#if UNITY_EDITOR
    [CustomEditor(typeof(KeyDomain))]
    public class KeyDomainEditor : Editor
    {
        public override void OnInspectorGUI()
        {
            // Draws the standard list and fields
            DrawDefaultInspector();

            var domain = (KeyDomain)target;

            EditorGUILayout.Space(15);

            // Adds the button with a slightly larger height for visibility
            if (GUILayout.Button("Generate Static Class", GUILayout.Height(30)))
            {
                domain.GenerateCode();
            }
        }
    }
#endif
}