using UnityEngine;

namespace SemanticKeys
{
    [CreateAssetMenu(fileName = "SemanticKeysSettings", menuName = "SemanticKeys/Settings")]
    public class SemanticKeysSettings : ScriptableObject
    {
        [Header("Storage Paths")]
        [Tooltip("Where new KeyDomain ScriptableObjects will be created.")]
        [SerializeField] private string _domainCreationPath = "Assets/Data/SemanticKeys";

        [Tooltip("Where the static C# classes will be generated.")]
        [SerializeField] private string _generatedCodePath = "Assets/Scripts/AutoGenerated";

        [Header("Code Generation")]
        [Tooltip("The namespace for the generated static classes.")]
        [SerializeField] private string _generatedNamespace = "Game.Constants";

        public string DomainCreationPath => _domainCreationPath;
        public string GeneratedCodePath => _generatedCodePath;
        public string GeneratedNamespace => _generatedNamespace;

        // Singleton-like access for Editor scripts
        public static SemanticKeysSettings GetOrCreateSettings()
        {
#if UNITY_EDITOR
            var guids = UnityEditor.AssetDatabase.FindAssets("t:SemanticKeysSettings");
            if (guids.Length > 0)
            {
                var path = UnityEditor.AssetDatabase.GUIDToAssetPath(guids[0]);
                return UnityEditor.AssetDatabase.LoadAssetAtPath<SemanticKeysSettings>(path);
            }
#endif

            // Fallback (In-memory only if not found) to prevent crashes
            var settings = CreateInstance<SemanticKeysSettings>();
            return settings;
        }
    }
}